- name: "Install {{ item }}"
  apt:
    name: "{{ item }}"
  loop:
    - zsh
    - curl
    - jq
    - httpie

- name: Install Dasel
  get_url:
    url: https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64
    dest: /usr/local/bin/dasel
    mode: '0755'